package com.example.model

object MeskotStrings {
    private val en = mapOf(
        "welcomeBack" to "Welcome back",
        "loginSub" to "Log in to see what your circle is sharing",
        "email" to "Email",
        "password" to "Password",
        "logIn" to "Log in",
        "noAccount" to "No account yet?",
        "signUpLink" to "Sign up",
        "joinTitle" to "Join Meskot",
        "joinSub" to "Create your window onto the community",
        "fullName" to "Full name",
        "createAccount" to "Create account",
        "hasAccount" to "Already have an account?",
        "logInLink" to "Log in",
        "noBioYet" to "No bio yet",
        "editProfile" to "Edit profile",
        "navFeed" to "Feed",
        "navFriends" to "Friends",
        "navMessages" to "Messages",
        "navGroups" to "Groups",
        "navPhotos" to "Photos",
        "composerPh" to "What's on your mind?",
        "addPhoto" to "Add photo/video",
        "post" to "Post",
        "emptyFeed" to "No posts yet — be the first to share something.",
        "loadingFeed" to "Loading feed…",
        "bio" to "Bio",
        "photo" to "Photo",
        "cancel" to "Cancel",
        "save" to "Save",
        "like" to "Like",
        "liked" to "Liked",
        "comment" to "Comment",
        "writeComment" to "Write a comment…",
        "send" to "Send",
        "logout" to "Log out",
        "justNow" to "just now",
        "minAgo" to "m ago",
        "hrAgo" to "h ago",
        "dayAgo" to "d ago",
        "fillFields" to "Please fill in all fields.",
        "postFailed" to "Couldn't post. Try again.",
        "profileSaved" to "Profile saved.",
        "posted" to "Posted.",
        "tabDiscover" to "Discover",
        "tabRequests" to "Requests",
        "tabMyFriends" to "My Friends",
        "searchPeople" to "Search people…",
        "noPeople" to "Nothing here yet.",
        "backToFeed" to "Back to feed",
        "noPostsYet" to "No posts yet.",
        "addFriend" to "Add friend",
        "requested" to "Requested",
        "cancelReq" to "Cancel request",
        "accept" to "Accept",
        "decline" to "Decline",
        "friendsLabel" to "Friends",
        "unfriend" to "Unfriend",
        "noRequests" to "No pending requests.",
        "noFriendsYet" to "No friends yet — find people in Discover.",
        "you" to "You",
        "incomingSub" to "wants to be friends",
        "messageBtn" to "Message",
        "noConvos" to "No conversations yet — message a friend from their profile.",
        "typeMessage" to "Type a message…",
        "backToMessages" to "Back to messages",
        "startedChat" to "Say hello 👋",
        "tabMyGroups" to "My Groups",
        "searchGroups" to "Search groups…",
        "createGroup" to "Create group",
        "noGroups" to "No groups yet — be the first to create one.",
        "groupName" to "Group name",
        "groupDesc" to "Description",
        "create" to "Create",
        "backToGroups" to "Back to groups",
        "joinToPost" to "Join this group to post and comment.",
        "noGroupPosts" to "No posts yet — start the conversation.",
        "join" to "Join",
        "leave" to "Leave",
        "member" to "Member",
        "members" to "members",
        "whatsHappening" to "Share something with the group…",
        "myAlbums" to "My Albums",
        "noAlbums" to "No albums yet.",
        "createAlbum" to "Create album",
        "albumTitle" to "Album title",
        "backToAlbums" to "Back to albums",
        "noMedia" to "No photos or videos yet.",
        "viewPhotos" to "View photos",
        "addMedia" to "Add photos/videos",
        "theirAlbums" to "Albums",
        "uploading" to "Uploading…",
        "items" to "items",
        "notifications" to "Notifications",
        "noNotifs" to "No notifications yet.",
        "notifLikeSuffix" to "liked your post",
        "notifCommentSuffix" to "commented on your post",
        "notifReqSuffix" to "sent you a friend request",
        "notifAcceptSuffix" to "accepted your friend request",
        "notifMsgSuffix" to "sent you a message",
        "notifReactSuffix" to "reacted to your post",
        "notifShareSuffix" to "shared your post",
        "notifTipSuffix" to "sent you a tip",
        "navAdmin" to "Admin",
        "adminDashboard" to "Admin Dashboard",
        "myDashboard" to "Dashboard",
        "tabOverview" to "Overview",
        "tabUsers" to "Users",
        "tabPosts" to "Posts",
        "tabGroupsAdmin" to "Groups",
        "statUsers" to "Users",
        "statPosts" to "Posts",
        "statGroupPosts" to "Group posts",
        "statGroupsAdmin" to "Groups",
        "statAlbums" to "Albums",
        "suspend" to "Suspend",
        "unsuspend" to "Unsuspend",
        "makeAdmin" to "Make admin",
        "removeAdmin" to "Remove admin",
        "deletePost" to "Delete",
        "deleteGroup" to "Delete",
        "accountSuspended" to "This account has been suspended.",
        "confirmDeletePost" to "Delete this post? This can't be undone.",
        "confirmDeleteGroup" to "Delete this group? This can't be undone.",
        "likesLabel" to "likes",
        "forgotPassword" to "Forgot password?",
        "resetPassTitle" to "Reset your password",
        "resetPassSub" to "Enter your email and we'll send you a reset link",
        "sendResetLink" to "Send reset link",
        "backToLogin" to "← Back to log in",
        "resetEmailSent" to "Reset link sent — check your inbox.",
        "verifyTitle" to "Verify your email",
        "verifySub" to "We sent a verification link to:",
        "ivVerified" to "I've verified — Continue",
        "resendEmail" to "Resend email",
        "useAnotherAccount" to "Use a different account",
        "verifyEmailSent" to "Verification email sent.",
        "pwHint" to "7–49 characters, with upper/lowercase letters, a number, and a symbol.",
        "pwTooShort" to "Password must be longer than 6 characters.",
        "pwTooLong" to "Password must be shorter than 50 characters.",
        "pwTooWeak" to "Password must include upper & lower letters, a number, and a symbol.",
        "share" to "Share",
        "sharedAPost" to "shared a post",
        "postShared" to "Shared to your feed.",
        "reply" to "Reply",
        "writeReply" to "Write a reply…",
        "menuTitle" to "Menu",
        "viewProfile" to "View your profile",
        "settingsPrivacy" to "Settings & privacy",
        "saved" to "Saved",
        "noSaved" to "Nothing saved yet.",
        "backToMenu" to "Back to menu",
        "createPost" to "Create post",
        "whoCanSee" to "Who can see your post?",
        "public" to "Public",
        "seeMore" to "… See more",
        "seeLess" to "See less",
        "tabInsights" to "Insights",
        "tabContent" to "Content",
        "tabEngagementDash" to "Engagement",
        "last28Days" to "Last 28 days",
        "postsMade" to "Posts made",
        "reactionsGot" to "Reactions received",
        "commentsGot" to "Comments received",
        "newFriends" to "New friends",
        "noEngagementYet" to "No engagement yet.",
        "support" to "Support",
        "supportCreator" to "Support this creator",
        "supportSub" to "100% goes directly to them via Chapa — Meskot takes no cut.",
        "customAmount" to "Custom amount (ETB)",
        "continueToPay" to "Continue to pay",
        "etbReceived" to "ETB received",
        "brandSubtitle" to "መስኮት · መስኮትህ ለማህበረሰብህ",
        "activeNow" to "Active now",
        "switchUser" to "Switch User",
        "demoUsers" to "Demo Accounts"
    )

    private val am = mapOf(
        "welcomeBack" to "እንኳን ደህና መጡ",
        "loginSub" to "ማህበረሰብዎ ምን እያካፈለ እንደሆነ ለማየት ይግቡ",
        "email" to "ኢሜይል",
        "password" to "የይለፍ ቃል",
        "logIn" to "ግባ",
        "noAccount" to "አካውንት የለዎትም?",
        "signUpLink" to "ይመዝገቡ",
        "joinTitle" to "ወደ መስኮት ይቀላቀሉ",
        "joinSub" to "ወደ ማህበረሰቡ የሚያዩበትን መስኮት ይፍጠሩ",
        "fullName" to "ሙሉ ስም",
        "createAccount" to "አካውንት ይፍጠሩ",
        "hasAccount" to "አካውንት አለዎት?",
        "logInLink" to "ይግቡ",
        "noBioYet" to "እስካሁን የመግለጫ ጽሁፍ የለም",
        "editProfile" to "መገለጫ አርትዕ",
        "navFeed" to "ዜና ምግብ",
        "navFriends" to "ጓደኞች",
        "navMessages" to "መልዕክቶች",
        "navGroups" to "ቡድኖች",
        "navPhotos" to "ፎቶዎች",
        "composerPh" to "ምን እያሰቡ ነው?",
        "addPhoto" to "ፎቶ/ቪዲዮ ጨምር",
        "post" to "ለጥፍ",
        "emptyFeed" to "እስካሁን ምንም ልጥፍ የለም — የመጀመሪያው ይሁኑ።",
        "loadingFeed" to "ዜና ምግብ በመጫን ላይ…",
        "bio" to "የመግለጫ ጽሁፍ",
        "photo" to "ፎቶ",
        "cancel" to "ይቅር",
        "save" to "አስቀምጥ",
        "like" to "ውደድ",
        "liked" to "ወድጃለሁ",
        "comment" to "አስተያየት",
        "writeComment" to "አስተያየት ይጻፉ…",
        "send" to "ላክ",
        "logout" to "ውጣ",
        "justNow" to "አሁን",
        "minAgo" to "ደቂቃ በፊት",
        "hrAgo" to "ሰዓት በፊት",
        "dayAgo" to "ቀን በፊት",
        "fillFields" to "እባክዎ ሁሉንም መስኮች ይሙሉ።",
        "postFailed" to "መለጠፍ አልተቻለም። እንደገና ይሞክሩ።",
        "profileSaved" to "መገለጫ ተቀምጧል።",
        "posted" to "ተለጥፏል።",
        "tabDiscover" to "ያግኙ",
        "tabRequests" to "ጥያቄዎች",
        "tabMyFriends" to "ጓደኞቼ",
        "searchPeople" to "ሰዎችን ይፈልጉ…",
        "noPeople" to "እስካሁን ምንም የለም።",
        "backToFeed" to "ወደ ዜና ምግብ ተመለስ",
        "noPostsYet" to "እስካሁን ምንም ልጥፍ የለም።",
        "addFriend" to "ጓደኛ ጨምር",
        "requested" to "ጥያቄ ተልኳል",
        "cancelReq" to "ጥያቄ ሰርዝ",
        "accept" to "ተቀበል",
        "decline" to "አትቀበል",
        "friendsLabel" to "ጓደኞች",
        "unfriend" to "ከጓደኝነት አስወግድ",
        "noRequests" to "ምንም ያልተመለሱ ጥያቄዎች የሉም።",
        "noFriendsYet" to "እስካሁን ጓደኛ የለም — በ«ያግኙ» ውስጥ ሰዎችን ይፈልጉ።",
        "you" to "እርስዎ",
        "incomingSub" to "የጓደኝነት ጥያቄ ልኳል",
        "messageBtn" to "መልእክት",
        "noConvos" to "እስካሁን ምንም ውይይት የለም — ከጓደኛዎ መገለጫ ገጽ መልእክት ይላኩ።",
        "typeMessage" to "መልእክት ይጻፉ…",
        "backToMessages" to "ወደ መልእክቶች ተመለስ",
        "startedChat" to "ሰላም ይበሉ 👋",
        "tabMyGroups" to "የእኔ ቡድኖች",
        "searchGroups" to "ቡድኖችን ይፈልጉ…",
        "createGroup" to "ቡድን ይፍጠሩ",
        "noGroups" to "እስካሁን ምንም ቡድን የለም — የመጀመሪያው ይሁኑ።",
        "groupName" to "የቡድን ስም",
        "groupDesc" to "መግለጫ",
        "create" to "ይፍጠሩ",
        "backToGroups" to "ወደ ቡድኖች ተመለስ",
        "joinToPost" to "ለመልጠፍና አስተያየት ለመስጠት ይህን ቡድን ይቀላቀሉ።",
        "noGroupPosts" to "እስካሁን ምንም ልጥፍ የለም — ውይይት ይጀምሩ።",
        "join" to "ይቀላቀሉ",
        "leave" to "ይውጡ",
        "member" to "አባል",
        "members" to "አባላት",
        "whatsHappening" to "ከቡድኑ ጋር የሆነ ነገር ያካፍሉ…",
        "myAlbums" to "የእኔ አልበሞች",
        "noAlbums" to "እስካሁን ምንም አልበም የለም።",
        "createAlbum" to "አልበም ይፍጠሩ",
        "albumTitle" to "የአልበም ርዕስ",
        "backToAlbums" to "ወደ አልበሞች ተመለስ",
        "noMedia" to "እስካሁን ምንም ፎቶ ወይም ቪዲዮ የለም።",
        "viewPhotos" to "ፎቶዎችን ይመልከቱ",
        "addMedia" to "ፎቶ/ቪዲዮ ጨምር",
        "theirAlbums" to "አልበሞች",
        "uploading" to "በመስቀል ላይ…",
        "items" to "ንጥሎች",
        "notifications" to "ማሳወቂያዎች",
        "noNotifs" to "እስካሁን ምንም ማሳወቂያ የለም።",
        "notifLikeSuffix" to "ልጥፍዎን ወድዷል",
        "notifCommentSuffix" to "በልጥፍዎ ላይ አስተያየት ሰጥቷል",
        "notifReqSuffix" to "የጓደኝነት ጥያቄ ልኮልዎታል",
        "notifAcceptSuffix" to "የጓደኝነት ጥያቄዎን ተቀብሏል",
        "notifMsgSuffix" to "መልእክት ልኮልዎታል",
        "notifReactSuffix" to "በልጥፍዎ ላይ ምላሽ ሰጥቷል",
        "notifShareSuffix" to "ልጥፍዎን አጋርቷል",
        "notifTipSuffix" to "ስጦታ ልኮልዎታል",
        "navAdmin" to "አስተዳደር",
        "adminDashboard" to "የአስተዳደር ዳሽቦርድ",
        "myDashboard" to "ዳሽቦርድ",
        "tabOverview" to "አጠቃላይ እይታ",
        "tabUsers" to "ተጠቃሚዎች",
        "tabPosts" to "ልጥፎች",
        "tabGroupsAdmin" to "ቡድኖች",
        "statUsers" to "ተጠቃሚዎች",
        "statPosts" to "ልጥፎች",
        "statGroupPosts" to "የቡድን ልጥፎች",
        "statGroupsAdmin" to "ቡድኖች",
        "statAlbums" to "አልበሞች",
        "suspend" to "አግድ",
        "unsuspend" to "እገዳ አንሳ",
        "makeAdmin" to "አስተዳዳሪ አድርግ",
        "removeAdmin" to "አስተዳዳሪነት አንሳ",
        "deletePost" to "ሰርዝ",
        "deleteGroup" to "ሰርዝ",
        "accountSuspended" to "ይህ አካውንት ታግዷል።",
        "confirmDeletePost" to "ይህ ልጥፍ ይሰረዝ? ይህ ተመልሶ አይመጣም።",
        "confirmDeleteGroup" to "ይህ ቡድን ይሰረዝ? ይህ ተመልሶ አይመጣም።",
        "likesLabel" to "ውዳሴዎች",
        "forgotPassword" to "የይለፍ ቃል ረሱ?",
        "resetPassTitle" to "የይለፍ ቃል ዳግም ያስጀምሩ",
        "resetPassSub" to "ኢሜይልዎን ያስገቡ የዳግም ማስጀመሪያ ማገናኛ እንልክልዎታለን",
        "sendResetLink" to "ማገናኛ ላክ",
        "backToLogin" to "← ወደ መግቢያ ተመለስ",
        "resetEmailSent" to "ማገናኛ ተልኳል — የገቢ መልእክት ሳጥንዎን ይመልከቱ።",
        "verifyTitle" to "ኢሜይልዎን ያረጋግጡ",
        "verifySub" to "የማረጋገጫ ማገናኛ ልከናል ወደ:",
        "ivVerified" to "አረጋግጫለሁ — ቀጥል",
        "resendEmail" to "እንደገና ላክ",
        "useAnotherAccount" to "ሌላ አካውንት ተጠቀም",
        "verifyEmailSent" to "የማረጋገጫ ኢሜይል ተልኳል።",
        "pwHint" to "ከ7 እስከ 49 ፊደላት፣ አቢይ እና ንዑስ ፊደላት፣ ቁጥር እና ምልክት ሊኖረው ይገባል።",
        "pwTooShort" to "የይለፍ ቃል ከ6 ፊደላት በላይ መሆን አለበት።",
        "pwTooLong" to "የይለፍ ቃል ከ50 ፊደላት በታች መሆን አለበት።",
        "pwTooWeak" to "የይለፍ ቃል አቢይ ፊደል፣ ንዑስ ፊደል፣ ቁጥር እና ምልክት ሊኖረው ይገባል።",
        "share" to "አጋራ",
        "sharedAPost" to "ልጥፍ አጋርቷል",
        "postShared" to "ወደ ገጽዎ ተጋርቷል።",
        "reply" to "መልስ",
        "writeReply" to "መልስ ይጻፉ…",
        "menuTitle" to "ማውጫ",
        "viewProfile" to "መገለጫዎን ይመልከቱ",
        "settingsPrivacy" to "ቅንብሮች እና ግላዊነት",
        "saved" to "የተቀመጡ",
        "noSaved" to "እስካሁን ምንም አልተቀመጠም።",
        "backToMenu" to "ወደ ማውጫ ተመለስ",
        "createPost" to "ልጥፍ ይፍጠሩ",
        "whoCanSee" to "ልጥፍዎን ማን ማየት ይችላል?",
        "public" to "ሁሉም",
        "seeMore" to "… ተጨማሪ ይመልከቱ",
        "seeLess" to "አሳንስ",
        "tabInsights" to "ግንዛቤዎች",
        "tabContent" to "ይዘት",
        "tabEngagementDash" to "ተሳትፎ",
        "last28Days" to "ያለፉት 28 ቀናት",
        "postsMade" to "የተለጠፉ ልጥፎች",
        "reactionsGot" to "የተገኙ ምላሾች",
        "commentsGot" to "የተገኙ አስተያየቶች",
        "newFriends" to "አዲስ ጓደኞች",
        "noEngagementYet" to "እስካሁን ምንም ተሳትፎ የለም።",
        "support" to "ድጋፍ",
        "supportCreator" to "ይህን ፈጣሪ ይደግፉ",
        "supportSub" to "100% ገንዘቡ በቻፓ በኩል ወደ እነሱ ይሄዳል — መስኮት ምንም አይወስድም።",
        "customAmount" to "ሌላ መጠን (ብር)",
        "continueToPay" to "ወደ ክፍያ ይቀጥሉ",
        "etbReceived" to "ብር ተገኝቷል",
        "brandSubtitle" to "መስኮት · መስኮትህ ለማህበረሰብህ",
        "activeNow" to "አሁን በመስመር ላይ",
        "switchUser" to "ተጠቃሚ ቀይር",
        "demoUsers" to "የሙከራ አካውንቶች"
    )

    fun get(key: String, lang: Language): String {
        return if (lang == Language.AM) {
            am[key] ?: en[key] ?: key
        } else {
            en[key] ?: key
        }
    }
}
